import React from "react";

export const LearnHowToCards = [
          { image: '/img/learn/klone_login.jpg',
            header: 'Short How-To: Hyak Klone Login', 
            caption: 'Log into Hyak Klone using ssh and 2-factor authentication with your UW NetID.',
            link: 'https://youtu.be/uHMPkHqigeg',
            isvideo: true,
          },
          { image: '/img/learn/klone_homedir.jpg',
            header: 'Short How-To: Hyak Home Directories', 
            caption: 'Learn the basics of your home directory on Hyak. This video is ideal for new users getting started with Hyak.',
            link: 'https://youtu.be/h--muyCPFHs',
            isvideo: true,
          },
          { image: '/img/learn/klone_fs.jpg',
            header: 'Short How-To: Navigating the Klone Filesystem', 
            caption: 'Commands like pwd, cd, and ls help you navigate directories, explore storage, and understand where your files live within the cluster.',
            link: 'https://youtu.be/VFGREiZ37x0',
            isvideo: true,
            isfeatured: true,
            featuredSortIndex: 5,
          },
        ];

export const LearnTutorialCards = [
          { image: '/img/learn/linux101.jpg',
            header: 'Tutorial: Linux Basics', 
            caption: 'Become familiar with the Linux command-line interface and Hyak\'s file system.',
            link: '/docs/hyak101/basics/syllabus',
            isfeatured: true,
            featuredSortIndex: 20,
          },
          { image: '/img/learn/slurm.jpg',
            header: 'Tutorial: Slurm', 
            caption: 'Learn how to schedule your computing jobs with Slurm.',
            link: '/docs/hyak101/basics/syllabus_slurm',
            isfeatured: true,
            featuredSortIndex: 50,
          },
          { image: '/img/learn/containers.jpg',
            header: 'Tutorial: Containers', 
            caption: 'Discover containers and containerization of software for usage on Hyak.',
            link: '/docs/hyak101/containers/syllabus',
            isfeatured: true,
            featuredSortIndex: 40,
          },
          { image: '/img/learn/advancedslurm.jpg',
            header: 'Tutorial: Advanced Slurm', 
            caption: 'Worked example demonstrating the use of scripting with Slurm job arrays.',
            link: '/docs/hyak101/basics/syllabus_advanced',
            isfeatured: true,
            featuredSortIndex: 60,
          },
          { image: '/img/learn/ood.jpg',
            header: 'Tutorial: Open OnDemand', 
            caption: 'Open OnDemand is a web-based portal that allows you to use your favorite graphical software on our supercomputers.',
            link: '/docs/ood/start',
            isfeatured: true,
            featuredSortIndex: 30,
          },
          { image: '/img/learn/ood.jpg',
            header: 'Tutorial: Open OnDemand', 
            caption: 'Open OnDemand is a web-based portal that allows you to use your favorite graphical software on our supercomputers.',
            link: '/docs/ood/start',
            isfeatured: true,
            featuredSortIndex: 30,
          },
        ];
        
export const LearnServicesCards = [
          { image: '/img/learn/klone_purchase.jpg',
            header: 'Hyak at UW', 
            caption: 'Purchasing Compute Resources on the Shared HPC Cluster, Klone.',
            link: 'https://youtu.be/kTMk_RgmdC0',
            isvideo: true,
          },
          { image: '/img/learn/kopah_purchase.jpg',
            header: 'Kopah Eligibility and Access', 
            caption: 'How to Get Started with UW\'s S3-API Compatible Storage Service.',
            link: 'https://youtu.be/E_IO7HTiOjg',
            isvideo: true,
          },
        ];
