import React from "react";

export const LearnHowToCards = [
          { image: '/img/learn/login.jpg',
            header: 'Hyak Klone Login', 
            caption: 'Log into Hyak Klone using ssh.',
            link: 'https://youtu.be/gbse1xqezqk',
            isvideo: true,
            isfeatured: true,
            featuredSortIndex: 3,
          },
          { image: '/img/learn/homedir.jpg',
            header: 'Hyak Home Directories', 
            caption: 'Hyak home directories 101.',
            link: 'https://youtu.be/OhLwqAZIBOo',
            isvideo: true,
            isfeatured: true,
            featuredSortIndex: 5,
          },
          { image: '/img/learn/filesystem.jpg',
            header: 'Hyak Klone Filesystem', 
            caption: 'Learn commands to navigate Klone.',
            link: 'https://youtu.be/VFGREiZ37x0',
            isvideo: true,
            isfeatured: true,
            featuredSortIndex: 10,
          },
          { image: '/img/learn/Slurm-thumbnail.jpg',
            header: 'Hyak Klone Slurm', 
            caption: 'An intro to Slurm on Hyak Klone.',
            link: 'https://youtu.be/jgHXB7IfGPQ?si=0lFpU_ujrQoUUmyb',
            isvideo: true,
            isfeatured: true,
            featuredSortIndex: 15,
          },
          { image: '/img/learn/kopah_short.jpg',
            header: 'Kopah S3 Storage - Quick Start', 
            caption: 'Getting started with Kopah S3 Storage.',
            link: 'https://youtu.be/xFONnv8TJ4s',
            isvideo: true,
            isfeatured: true,
            featuredSortIndex: 20,
          },
        ];

export const LearnTutorialCards = [
          { image: '/img/learn/linux_fundamentals.jpg',
            header: 'Tutorial: Linux Fundamentals', 
            caption: 'Become familiar with the Linux command-line interface and Hyak\'s file system.',
            link: 'https://github.com/UWrc/linux-fundamentals',
            isfeatured: true,
            featuredSortIndex: 20,
          },

          { image: '/img/learn/conda_ws.jpg',
            header: 'Tutorial: Conda & Jupyter', 
            caption: 'Managing Conda environments & using them effectively in Jupyter Notebooks.',
            link: 'https://github.com/UWrc/jupyter-tutorial',
            isfeatured: true,
            featuredSortIndex: 30,
          },

          { image: '/img/learn/slurm.jpg',
            header: 'Tutorial: Slurm', 
            caption: 'Learn how to schedule your computing jobs with Slurm.',
            link: '/docs/hyak101/basics/syllabus_slurm',
            isfeatured: false,
          },
          
          { image: '/img/learn/advancedslurm.jpg',
            header: 'Tutorial: Advanced Slurm', 
            caption: 'Worked example demonstrating the use of scripting with Slurm job arrays.',
            link: '/docs/hyak101/basics/syllabus_advanced',
            isfeatured: false,
          },

          { image: '/img/learn/till_onboard.jpg',
            header: 'Tutorial: Tillicum Onboarding', 
            caption: 'Dive into the Tillicum GPU cluster with this guided introduction.',
            link: 'https://github.com/UWrc/tillicum-onboarding',
            isfeatured: true,
            isvideo : false,
            featuredSortIndex: 35,
          },

          { image: '/img/learn/till_slurm.jpg',
            header: 'Tutorial: Tillicum Slurm', 
            caption: 'Getting started using Slurm on the Tillicum GPU cluster.',
            link: 'https://github.com/UWrc/tillicum-slurm',
            isfeatured: true,
            isvideo : false,
            featuredSortIndex: 40,
          },

          { image: '/img/learn/till_containers.jpg',
            header: 'Tutorial: Tillicum Containers', 
            caption: 'Learn how to run software on Tillicum using Apptainer containers.',
            link: 'https://github.com/UWrc/tillicum-containers/',
            isfeatured: true,
            featuredSortIndex: 50,
          },

          { image: '/img/learn/r_rstudio_ws.jpg',
            header: 'Tutorial: R & Rstudio on Hyak Klone', 
            caption: 'Studio via Open OnDemand and custom R containers.',
            link: 'https://github.com/UWrc/r_rstudio_tutorial',
          },
          
          { image: '/img/learn/containers.jpg',
            header: 'Tutorial: Containers', 
            caption: 'Discover containers and containerization of software for usage on Hyak.',
            link: '/docs/hyak101/containers/syllabus',
            isfeatured: false,
          },

          { image: '/img/learn/docker_ws_icon.jpg',
            header: 'Tutorial: Docker Containers', 
            caption: 'Dive into containerization with Docker for research computing.',
            link: 'https://github.com/UWrc/docker-tutorial',
            isfeatured: false,
          },

          { image: '/img/learn/ood.jpg',
            header: 'Tutorial: Open OnDemand', 
            caption: 'Use your favorite graphical software on our supercomputers.',
            link: '/docs/ood/start',
            isfeatured: false,
          },
          { image: '/img/learn/ood_jup.jpg',
            header: 'Tutorial: Jupyter + OOD', 
            caption: 'Use Open OnDemand to launch Juptyer Lab.',
            link: 'https://youtu.be/ztGz4I_EMq8',
            isvideo: true,
          },
          { image: '/img/learn/pytorch.jpg',
            header: 'Tutorial: Multi-GPU PyTorch Workshop', 
            caption: 'Using Pytorch DDP to scale GPU workloads.',
            link: 'https://youtu.be/uDKEIoBG5w0',
            isvideo: true,
          },
          { image: '/img/learn/plotting1.jpg',
            header: 'Tutorial: Python Part 1', 
            caption: 'Dataframes & Arrays.',
            link: 'https://youtu.be/e0oecJ_j87Y',
            isvideo: true,
          },
          { image: '/img/learn/plotting2.jpg',
            header: 'Tutorial: Python Part 2', 
            caption: 'Data Visualization & Plotting.',
            link: 'https://youtu.be/lfOIbEjKZQg',
            isvideo: true,
          },
          { image: '/img/learn/deep_learning.jpg',
            header: 'Tutorial: Deep Learning', 
            caption: 'Deep learning frameworks and computing environments.',
            link: 'https://youtu.be/YhsV6dGi5RU',
            isvideo: true,
          },
          { image: '/img/learn/s3cmd.jpg',
            header: 'Tutorial: s3cmd & s5cmd', 
            caption: 'Data transfer workflow with Kopah S3.',
            link: 'https://youtu.be/xT2RcNrvTPw',
            isvideo: true,
          },
          { image: '/img/learn/globus.jpg',
            header: 'Tutorial: Globus', 
            caption: 'Data transfer workflow with Kopah S3.',
            link: 'https://youtu.be/bheKdLOvSs4',
            isvideo: true,
          },
          { image: '/img/learn/boto3.jpg',
            header: 'Tutorial: Boto3', 
            caption: 'Programmatically interact with Kopah S3.',
            link: 'https://youtu.be/yBgZAU_qyRg',
            isvideo: true,
          },
        ];
        
export const LearnServicesCards = [
          { image: '/img/learn/klone_purchase.jpg',
            header: 'Hyak at UW', 
            caption: 'Purchasing Compute Resources on the Shared HPC Cluster, Klone.',
            link: 'https://youtu.be/kTMk_RgmdC0',
            isvideo: true,
          },
          { image: '/img/learn/kopah_purchase.jpg',
            header: 'Kopah Eligibility and Access', 
            caption: 'How to Get Started with UW\'s S3-API Compatible Storage Service.',
            link: 'https://youtu.be/E_IO7HTiOjg',
            isvideo: true,
          },
        ];

export const LearnSpotlightCards = [
          { image: '/img/learn/spotlights/icu.png',
            header: 'UW Institute for Medical Data Science', 
            caption: 'Using machine learning to optimize prediction of extubation failure and clinical action',
            link: 'https://www.youtube.com/watch?v=QnJBSsP9sh4',
            isvideo: true,
          },

          { image: '/img/learn/spotlights/denolle.jpg',
            header: 'Denolle Quake Lab', 
            caption: 'A Global Database of Seismic Phases with Cloud Computing',
            link: 'https://youtu.be/XVpll-kSXuY',
            isvideo: true,
          },
          { image: '/img/learn/spotlights/jayadevlab.jpg',
            header: 'Jayadev Lab', 
            caption: 'Advancing Alzheimer\'s Research with UW\'s Supercomputer',
            link: 'https://youtu.be/9w8A7FpDyRs',
            isvideo: true,
          },
          { image: '/img/learn/spotlights/cardss.jpg',
            header: 'Cardiac Systems Simulation Laboratory', 
            caption: 'Cardiovascular Disease and UW\'s Supercomputer',
            link: 'https://youtu.be/qpyin6iakLw',
            isvideo: true,
          },
          { image: '/img/learn/spotlights/qlora.jpg',
            header: 'QLoRA', 
            caption: 'Efficient Finetuning of Quantized LLMs',
            link: 'https://youtu.be/G8mn5SVgThA',
            isvideo: true,
          },
        ];

export const LearnSpecialCards = [
          { image: '/img/learn/special/till_launch.jpg',
            header: 'Tillicum Cluster Launch Event', 
            caption: 'Event recap featuring NVIDIA and UW researchers',
            link: 'https://youtu.be/uUbPIznMgAE',
            isvideo: true,
          },
  
          { image: '/img/learn/special/simmons1.jpg',
            header: 'Userspace Package Management', 
            caption: 'GPU in EDU 2025 Session 1',
            link: 'https://youtu.be/ejas1s2rnKk',
            isvideo: true,
          },
          { image: '/img/learn/special/finch.jpg',
            header: 'Empowering Research', 
            caption: 'GPU in EDU 2025 Session 2',
            link: 'https://youtu.be/0C1-s1d_bq0',
            isvideo: true,
          },
          { image: '/img/learn/special/alkan.jpg',
            header: 'NVIDIA RAPIDS', 
            caption: 'GPU in EDU 2025 Session 3',
            link: 'https://youtu.be/ujImFQydq9U',
            isvideo: true,
          },
          { image: '/img/learn/special/simmons2.jpg',
            header: 'GPU Computing in Curricula', 
            caption: 'GPU in EDU 2025 Session 4',
            link: 'https://youtu.be/86U7U-1YHt8',
            isvideo: true,
          },
        ];
